language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t jlucar/docker-react .

script:
  - docker run -e CI=true jlucar/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_namne: "elasticbeanstalk-us-west-2-114795878898"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY